// Copyright 2024 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.

/**
 * Configuration for the Synchronised Storage Service.
 */
export interface ISynchronisedStorageServiceConfig {
	/**
	 * The key to use for the remote synchronised storage, the initial item will have been
	 * generated by a trusted node.
	 */
	synchronisedStorageKey: string;

	/**
	 * The id of the identity method to use when signing/verifying changesets.
	 * @default synchronised-storage-assertion
	 */
	synchronisedStorageMethodId?: string;

	/**
	 * How often to check for entity updates in milliseconds.
	 * @default 300000 (5 minutes)
	 */
	entityUpdateIntervalMs?: number;

	/**
	 * Is this a node that has permission to write to the verifiable storage?
	 * @default false
	 */
	isTrustedNode?: boolean;

	/**
	 * Interval to perform consolidation of changesets, only used if isTrustedNode is set.
	 * @default 300000 (5 minutes)
	 */
	consolidationIntervalMs?: number;

	/**
	 * The number of entities to process in a single consolidation batch.
	 * @default 1000
	 */
	consolidationBatchSize?: number;
}
