// Copyright 2024 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.

/**
 * Configuration for the Synchronised Storage Service.
 */
export interface ITrustedSynchronisedStorageServiceConfig {
	/**
	 * The key to use for the remote synchronised storage, the initial item will have been
	 * generated by a trusted node.
	 */
	synchronisedStorageKey: string;

	/**
	 * The id of the identity method to use when signing/verifying changesets.
	 * @default synchronised-storage-assertion
	 */
	synchronisedStorageMethodId?: string;
}
