name: Build, Lint, Test, Docs Next

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  dist:
    runs-on: ubuntu-latest

    env:
      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}

    services:
      scylladb:
        image: scylladb/scylla:5.4.9
        ports:
          - 9042:9042

      dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000

      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_PASSWORD: password

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # TODO: Remove once we have a way to pass flags in the services section
      - name: Start Firestore Emulator
        run: |
          docker run -d --name twin-entity-storage-firestore -p 8080:8080 gcr.io/google.com/cloudsdktool/cloud-sdk:emulators gcloud beta emulators firestore start --host-port=0.0.0.0:8080

      - name: Increase aio-max-nr
        # Increase the maximum number of asynchronous I/O (AIO) requests that can be queued to
        # the kernel. This is necessary for the CosmosDB Emulator to function properly, as it
        # requires a higher limit for I/O operations.
        # Reference: https://man7.org/linux/man-pages/man5/proc.5.html#fs.aio-max-nr
        run: |
          echo 1048576 | sudo tee /proc/sys/fs/aio-max-nr

      - name: Pull CosmosDB Emulator Docker Image
        run: |
          docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest

      - name: Run CosmosDB Emulator
        run: |
          docker run \
            --publish 8081:8081 \
            --publish 10250-10255:10250-10255 \
            --name twin-entity-storage-cosmos \
            --detach \
            --platform=linux/amd64 --memory=3g --cpus=2.0 \
            mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest

      - name: Wait for CosmosDB Emulator to be Ready
        run: |
          for i in {1..30}; do
            if nc -zv localhost 8081; then
              echo "CosmosDB emulator is ready!"
              break
            fi
            echo "Waiting for CosmosDB emulator to be ready..."
            sleep 5
          done

      - name: Restore root node_modules from cache
        id: node-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run Lint and Dist
        run: |
          npm run lint
          npm run dist
