name: Publish Prod All Packages

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    if: github.ref == 'refs/heads/main'

    env:
      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}

    strategy:
      max-parallel: 1
      matrix:
        package:
          [
            'packages/entity-storage-models',
            'packages/entity-storage-connector-memory',
            'packages/entity-storage-connector-file',
            'packages/entity-storage-connector-scylladb',
            'packages/entity-storage-connector-dynamodb',
            'packages/entity-storage-service',
            'packages/entity-storage-rest-client',
            'packages/entity-storage-connector-gcp-firestore',
            'packages/entity-storage-connector-cosmosdb',
            'packages/entity-storage-connector-mysql',
            'packages/entity-storage-connector-mongodb',
            'packages/entity-storage-connector-postgresql'
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      # Start PostgreSQL service only for PostgreSQL package
      - name: Start PostgreSQL Service
        if: matrix.package == 'packages/entity-storage-connector-postgresql'
        run: |
          docker run -d --name twin-entity-storage-postgresql -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -p 5432:5432 postgres:latest

      # Start ScyllaDB service only for ScyllaDB package
      - name: Start ScyllaDB Service
        if: matrix.package == 'packages/entity-storage-connector-scylladb'
        run: |
          docker run -d --name twin-entity-storage-scylladb -p 9042:9042 scylladb/scylla:5.4.9

      # Start DynamoDB service only for DynamoDB package
      - name: Start DynamoDB Service
        if: matrix.package == 'packages/entity-storage-connector-dynamodb'
        run: |
          docker run -d --name twin-entity-storage-dynamodb -p 8000:8000 amazon/dynamodb-local:latest

      # Start MySQL service only for MySQL package
      - name: Start MySQL Service
        if: matrix.package == 'packages/entity-storage-connector-mysql'
        run: |
          docker run -d --name twin-entity-storage-mysql -e MYSQL_ROOT_PASSWORD=password -p 3306:3306 mysql:latest

      # Start MongoDB service only for MongoDB package
      - name: Start MongoDB Service
        if: matrix.package == 'packages/entity-storage-connector-mongodb'
        run: |
          docker run -d --name twin-entity-storage-mongo -p 27017:27017 mongo:latest

      # Start Firestore service only for Firestore package
      - name: Start Firestore Emulator
        if: matrix.package == 'packages/entity-storage-connector-gcp-firestore'
        run: |
          docker run -d --name twin-entity-storage-firestore -p 8080:8080 gcr.io/google.com/cloudsdktool/cloud-sdk:emulators gcloud beta emulators firestore start --host-port=0.0.0.0:8080

      - name: Increase aio-max-nr
        if: matrix.package == 'packages/entity-storage-connector-cosmosdb'
        # Increase the maximum number of asynchronous I/O (AIO) requests that can be queued to
        # the kernel. This is necessary for the CosmosDB Emulator to function properly, as it
        # requires a higher limit for I/O operations.
        # Reference: https://man7.org/linux/man-pages/man5/proc.5.html#fs.aio-max-nr
        run: |
          echo 1048576 | sudo tee /proc/sys/fs/aio-max-nr

      # Start CosmosDB service only for CosmosDB package
      - name: Pull CosmosDB Emulator Docker Image
        if: matrix.package == 'packages/entity-storage-connector-cosmosdb'
        run: |
          docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest

      - name: Run CosmosDB Emulator
        if: matrix.package == 'packages/entity-storage-connector-cosmosdb'
        run: |
          docker run \
            --publish 8081:8081 \
            --publish 10250-10255:10250-10255 \
            --name twin-entity-storage-cosmos \
            --detach \
            --platform=linux/amd64 --memory=3g --cpus=2.0 \
            mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest

      - name: Wait for CosmosDB Emulator to be Ready
        if: matrix.package == 'packages/entity-storage-connector-cosmosdb'
        run: |
          for i in {1..30}; do
            if nc -zv localhost 8081; then
              echo "CosmosDB emulator is ready!"
              break
            fi
            echo "Waiting for CosmosDB emulator to be ready..."
            sleep 5
          done

      - name: Remove Mono-Repo Node Modules
        run: |
          rm package.json
          rm package-lock.json

      - name: Check package version does not contain -next
        run: |
          cd ${{ matrix.package }}
          PACKAGE_VERSION=$(cat package.json | jq '.version' | tr -d '"')
          echo Package Version $PACKAGE_VERSION
          if [[ $PACKAGE_VERSION == *"-next"* ]]; then
            echo "Error: package version contains -next"
            exit 1
          fi

      - name: Run Dist
        run: |
          cd ${{ matrix.package }}
          npm install
          npm run dist

      - name: Cleanup package properties
        run: |
          cd ${{ matrix.package }}
          npm pkg delete scripts
          npm pkg delete devDependencies

      - name: Publish
        run: |
          cd ${{ matrix.package }}
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
